lim8662/hackerrank/type-of-triangle.sql
lim8662/leetcode/leet-26.ts
lim8662/leetcode/leet-9.ts

[문제 보러가기](https://leetcode.com/problems/palindrome-number/)
투포인터로 풀었습니다.
```typescript
function removeDuplicates(nums: number[]): number {
let front: number = 0;
let back: number = 1;
while(back < nums.length) {
if(nums[front] !== nums[back]) {
front++;
nums[front] = nums[back];
back++
} else back++
}
return front + 1;
};
```
문제는 어렵지 않았지만 해석이 어려웠습니다. 영어공부가 필요합니다

임영찬 : leetcode 26 Remove Duplicates from Sorted Array

---

hyeonsook95/baekjoon/1018.js

[문제 보러가기](https://www.acmicpc.net/problem/1018)
처음에는 단순히 옆의 값과 비교하는 방식으로 count를 했습니다. 하지만, 첫 번째 칸이 맞지 않을 수 있고 그로 인해 비교해야 할 대상이 양 옆이 아니라는 것을 깨달았습니다.
체스판의 크기가 8*8로 고정되어 있고, 크기가 고정되어 있고 패턴이 같다면 정답이 2개로 고정된다는 아이디어를 얻었습니다.
그래서 `W`로 시작하는 체스판과 `B`로 시작하는 체스판을 만들어 주어진 입력과 정답 체스판을 비교하여 다른 칸의 개수를 카운트했습니다.
```javascript
const [n, m] = input[0].split(' ').map(num => parseInt(num));
var minCount = 8 * 8;
var maps = [];
for (r = 0; r < n; r++) {
maps.push(input[r + 1].trim());
}
const whiteAns = [
'WBWBWBWB',
'BWBWBWBW',
'WBWBWBWB',
'BWBWBWBW',
'WBWBWBWB',
'BWBWBWBW',
'WBWBWBWB',
'BWBWBWBW',
];
const blackAns = [
'BWBWBWBW',
'WBWBWBWB',
'BWBWBWBW',
'WBWBWBWB',
'BWBWBWBW',
'WBWBWBWB',
'BWBWBWBW',
'WBWBWBWB',
]
for (r …
```

하현숙: boj 1018 체스판 다시 칠하기

---

hyeonsook95/leetcode/17.ts

[문제 보러가기](https://leetcode.com/problems/letter-combinations-of-a-phone-number/)
```typescript
function letterCombinations(digits: string): string[] {
var results = [];
// dictionary 형식으로 숫자별 문자 리스트 선언
const digitsObjects = {
'2': ['a', 'b', 'c'],
'3': ['d', 'e', 'f'],
'4': ['g', 'h', 'i'],
'5': ['j', 'k', 'l'],
'6': ['m', 'n', 'o'],
'7': ['p', 'q', 'r', 's'],
'8': ['t', 'u', 'v'],
'9': ['w', 'x', 'y', 'z']
};
// 재귀로 조합 구현
// 파라미터로 문자를 조합해야 할 digits의 idx 값을 전달 받음
const combination = function (idx, result) {
if (digits.length === result.length) {
return results.push(result);
}
var chars = digitsObjects[digits[idx]];
for (var char in chars) {
combination(idx + 1, result + chars[char]);
}
};
var chars = digitsObjects[digits[0]];
for (var char in chars) {
combination(1, chars[char]);
}
return …
```

하현숙 leetcode 17 조합 Letter Combinations of a Phone Number

---

hyeonsook95/leetcode/1518.ts

[문제 보러가기](https://leetcode.com/problems/water-bottles/)
이 문제의 첫 번째 포인트는 **마신 물 병을 새로운 물 병으로 교환** 하는 것이라 분석했습니다. 마신 물 병은 공교롭게도 1:1 교환이 아니었고, 그렇다면 나눗셈 연산을 해야겠구나 생각했습니다. 나눗셈 연산은 언제나 1/0이 되지 않도록 주의해야 하는 연산이므로 if 문으로 에러를 방지했습니다.
```python
if (numBottles / numBottles의 몫) > 0:
몫, 나머지 = numBottles/numExchange
numBottles = 몫 + 나머지
마신양 += 몫
마신양 += numBottles
```
이 문제의 두 번째 포인트는 **새로운 물 병을 마시고 나면 교환할 수 있는 물 병이 된다.** 라는 점이었습니다. 현실에서는 당연하게 이루어지는 점이지만 알고리즘 세계에서는 조건으로 주어지지 않으면 고려하지 않아도 되는 사항이죠.
여기에서는 조건으로 주어졌기 때문에 교환이 불가능할 때까지 이 행위를 반복해야 한다는 것을 알게 됩니다. 따라서 그 위에 반복문을 씌워줍니다.
```python
while (조건):
...
```
반복문을 사용할 때는 언제까지 반복을 할 것인지 조건을 지정해주는 일이 중요합니다. 아니면 무한 루프에 빠지게 됩니다.
이 반복문은 내부의 내용이 문제에서 요구한 조건을 만족하는 한 계속해서 동작해야 합니다. 내부의 내용은 `마신 물 병을 새로운 물 병으로 교환`하는 내용이므로  `마신 물 병을 새로운 물 병으로 교환`하는 일이 언제까지 동작할 수 있는지 …

하현숙 : leetcode 1518 구현 Water Bottles

---

hyeonsook95/leetcode/181.sql

[문제 보러가기](https://leetcode.com/problems/employees-earning-more-than-their-managers/)
```sql
SELECT e.name as Employee
FROM Employee as e
WHERE e.salary > (SELECT m.salary
FROM Employee as m
WHERE m.id = e.managerId  );
```
WHERE 에서 또 다른 SELECT를 사용하는 것은 문제 풀이를 할 때 외에는 자주 사용하지 않아서 재미있었습니다.

하현숙 leetcode 181 sql Employees Earning More Than Their Managers

---

lim8662/leetcode/leet-181.sql

[문제 보러가기](https://leetcode.com/problems/employees-earning-more-than-their-managers/)
```sql
select sub.name as Employee
from Employee as sub
left join (select id, salary from Employee) as boss
on sub.managerId = boss.id
where sub.salary > boss.salary;
```
서브쿼리로 구한 상사의 봉급을 left join하고 
상사의 봉급보다 봉급이 높은 직원의 이름을 출력합니다. 
단순한 조인 문제라 무난했습니다.

임영찬 : leet 181 Employees Earning More Than Their Managers

---

lim8662/leetcode/leet-1518.ts

[문제 보러가기](https://leetcode.com/problems/water-bottles/)
```typescript
function numWaterBottles(numBottles: number, numExchange: number): number {
let total = numBottles; // 마신 병의 총합
let empty = total; // 빈 병의 수
let full = 0; // 교환해서 받은 병의 수
while (true) {
full =  Math.floor(empty / numExchange); // 빈 병을 새 병으로 교환
if (full === 0) break;
empty = empty % numExchange; // 교환 후 남은 빈병
// 교환받은 병 다 비움
empty += full; 
total += full;
}
return total;
};
```
수학문제로 나머지와 몫을 구해서 시뮬레이션을 하는 문제입니다.
typescript는 나누기 연산을 하는 경우 실수값이 리턴되므로 
`Math.floor()`함수를 사용해 소수점 내림을 하여 몫을 구했습니다.
단순한 수학문제라 문제없이 풀었습니다.

임영찬 : leet 1518 Water Bottles

---

lim8662/leetcode/leet-17.ts

[문제 보러가기](https://leetcode.com/problems/letter-combinations-of-a-phone-number/)
1. 선언부
```typescript
const map = new Map([
['2', ['a', 'b', 'c']],
['3', ['d', 'e', 'f']],
['4', ['g', 'h', 'i']],
['5', ['j', 'k', 'l']],
['6', ['m', 'n', 'o']],
['7', ['p', 'q', 'r','s']],
['8', ['t', 'u', 'v']],
['9', ['w', 'x', 'y', 'z']] 
]);
let answer: string[] = []; 
```
입력받은 숫자에 대응하는 문자들을 Map에 저장해두었습니다.
그리고 반환할 정답 배열을 선언하고 빈 배열로 초기화하였습니다.
2. 구현부
```typescript
function letterCombinations(digits: string): string[] {
answer.length = 0; // 정답 배열 초기화
// 입력받은 숫자가 있으면 모든 문자 조합을 구함
if(digits.length) comb(digits, 0, '');  
return answer;
}
// 재귀로 조합 구현
function comb(digits: string, idx: number, str: string) {
if (idx === digits.length) { // 문자 조합이 완성되면 정답 배열에 추가
answer.push(str);
return;
}
// 현재 숫자로 가능한 문자 배열 …
```

임영찬 : leet 17 Letter Combinations of a Phone Number

---

hyeonsook95/baekjoon/2630.js

[문제 보러가기](https://www.acmicpc.net/problem/2630)
처음 생각한 아이디어는 1 -> 2 -> 4 -> 8 -> ... -> 128 까지 색종이의 범위를 늘려가면서, 해당 범위 내의 색을 검사하고, 색이 일치하여 검사된 범위를 `visited` 변수에 체크하도록 하였습니다.
그러나 이 아이디어는 범위의 시작 점이 자유롭지 않고, 일정하게 정해져 있다는 점을 간과한 잘못된 아이디어였습니다. 
그 후 생각한 아이디어는 일정하게 정해진 시작점을 N의 크기가 줄어들 때마다 구하는 방법이었습니다.
이 아이디어를 떠올리고 나서는 쉽게 아래의 코드를 설계할 수 있었습니다.
```javascript
const N = parseInt(input.shift());
const maps = input.map(nums => nums.split(' ').map(num => parseInt(num)));
// 정답 초기화
var answer = [0, 0];
// 재귀 함수
function cutPaper(startR, startC, d) {
// 종이의 면적이 적어서 자를 수 없거나, 해당 범위의 색이 모두 같을 경우 종료
if (d == 1 || checkColor(startR, startC, d)) {
answer[maps[startR][startC]] += 1;
return;
}
// N을 나눈 값을 index에 대응하기 위해 ceil로 …
```

하현숙 : boj 2630 색종이 만들기

---

hyeonsook95/baekjoon/10250.js

[문제 보러가기](https://www.acmicpc.net/problem/10250)
```javascript
const testCase = parseInt(input[0]);
for (var t = 0; t < testCase; t++) {
const [h, w, guests] = input[t + 1].split(' ').map(num => parseInt(num));
var floor = guests % h;
var room = Math.floor(guests / h);
if (floor == 0) {
floor = h;
room -= 1;
}
console.log(floor * 100 + (room + 1));
}
```
높이 이동을 고려하지 않고, 호텔의 모든 방이 항상 비어있는 상태로 시작하는 문제였기 때문에 간단히 수학적 연산으로 해결할 수 있을 것이라 생각했습니다.
손님이 채워지는 순서가 한 칸의 1층부터 끝층까지 채워진 후 다음 칸으로 넘어가는 방식이었기 때문에 나눗셈과 나머지 연산을 통해 구현하였습니다.
문제에서 주어지는 조건의 끝 부분을 고려하지 못해서 시간이 좀 걸렸습니다.
결국 질문 검색에서 특수 케이스를 찾아서 해결했습니다.

하현숙: boj 10250 ACM 호텔

---

hyeonsook95/hackerrank/binary_tree_nodes.sql

[문제 보러가기](https://www.hackerrank.com/challenges/binary-search-tree-1/problem?isFullScreen=true)
```sql
SELECT N, 
CASE
WHEN P IS NULL THEN 'Root'
WHEN (SELECT COUNT(*)
FROM BST AS CBST
WHERE CBST.P = PBST.N) = 0 THEN 'Leaf'
ELSE 'Inner'
END
FROM BST AS PBST
ORDER BY N;
```
`CASE` 문을 사용하여 조건에 해당하는 노드의 이름을 출력하였습니다. 
`Leaf`는 해당 노드가 Parent로 존재하지 않아야 하기 때문에 `CASE` 문 안에 `SELECT`를 사용하여 Parent로 사용하는 노드의 개수를 구하여 조건을 검사했습니다.
Join으로 할 수 있을 것 같았는데, 실패했습니다. 😞

하현숙 hackerrank Binary Tree Nodes

---

lim8662/boj/boj-10250.ts

[문제 보러가기](https://www.acmicpc.net/problem/10250)
문제에서 주어진 규칙대로 방 배정을 하고
마지막 N번째 손님의 방 번호를 구하는 문제입니다.
층 수보다 방 번호가 낮은 것이 우선시 되므로 
아랫층부터 방 번호가 같은 모든 층의 방을 배정한 후
방 번호를 증가 시키며 배정된 방의 수를 카운트 하였습니다.
배정 된 방의 수가 N개가 되면 그 때의  층 수와 방 번호를 조합하여 리턴합니다.
```typescript
const rl = require("readline").createInterface({
input: process.stdin,
output: process.stdout,
});
let input: string[] = [];
rl.on("line", function (line: string) {
input.push(line);
}).on("close", function () {
const T: number = parseInt(input.shift()!);
for (let tc = 0; tc < T; tc++) 
console.log(getLastRoomNo(input[tc]));
process.exit();
});
function getLastRoomNo(inputRow: string): number {
const [h, w, n] = inputRow.trim().split(" ").map((el: string) => parseInt(el));
let roomCnt = 0;
for (let roomNo = 1; roomNo <= w; roomNo++) 
for …
```

임영찬 : boj 10250 ACM 호텔

---

lim8662/hackerrank/binary-tree-nodes.sql

[문제 보러가기](https://www.hackerrank.com/challenges/binary-search-tree-1/problem?isFullScreen=true)
루트 노드, 리프 노드 , 나머지 3가지 경우로 나누어 
case문으로 다중분기 처리를 하였습니다.
```sql
select N, (
case 
when P is null then 'Root'
when N not in (select distinct P from BST where P is not null) then 'Leaf'
else 'Inner'
end
) from BST
order by N
```
`not in`을 사용할 경우 이 문제 처럼 조건의 범위에 `null`이 포함되는 경우에는 
내부 로직이 `N  != null and ...`이 되므로 무조건 false가 됩니다.
그래서 `where P is not null` 조건으로 null을 제거해줍니다.

임영찬 hack Binary Tree Nodes

---

lim8662/boj/boj-2630.ts

[문제 보러가기](https://www.acmicpc.net/problem/2630)
재귀 호출을 활용하는 분할 정복법으로 풀었습니다.
색종이를 4분할하고 좌측상단을 기준 좌표로 하여 
분할된 조각의 크기만큼의 범위가 색이 같은지 확인하고  
다르다면 다시 분할을 수행합니다.
종료조건으로는 만약 범위 크기가 1이거나  
범위의 색이 같다면 해당 색의 조각의 수를 카운트 합니다.
```typescript
const readline = require("readline");
const rl = readline.createInterface({
input: process.stdin,
output: process.stdout,
});
let input: string[] = [];
let paper: string[][] = [];
let whitePieceCnt: number = 0; // 흰 종이 조각 수
let bluePieceCnt: number = 0; // 파란 종이 조각 수
rl.on("line", function (line: string) {
input.push(line);
}).on("close", function () {
input.shift();
paper = input.map((row) => row.split(" "));
let N = input.length;
division(0, 0, N);
console.log(whitePieceCnt);
console.log(bluePieceCnt);
process.exit();
});
});
let input: number[] = []; …
```

임영찬 : boj 2630 색종이 만들기

---

hyeonsook95/leetcode/20.py
hyeonsook95/leetcode/20.ts

[문제 보러가기](https://leetcode.com/problems/valid-parentheses/)
Parentheses 문제는 학부과정에서 스택을 설명하는데에도 사용되기 때문에 바로 스택을 떠올려 문제를 풀었습니다.
Parentheses를 한 쌍씩 짝지어 dictionary에 담아 한 개의 값이 들어오면 바로 짝을 출력할 수 있도록 하였습니다.
그리고 스택에 들어있는 한 개의 값이 짝을 찾지 못하거나, 짝을 만나지 못한 상태에서 다른 종류의 다른 방향의 parentheses가 스택에 들어오면 종료하도록 하였습니다.
```typesctipt
function isValid(s) {
var parentheses = { ")": "(", "]": "[", "}": "{" };
var temp = [];
for (var char of s) {
if ("([{".indexOf(char) > -1) {
temp.push(char);
}
else {
if (temp.length === 0) {
return false;
}
var top = temp.pop();
if (top !== parentheses[char]) {
return false;
}
}
}
if (temp.length !== 0) {
return false;
}
return true;
};
console.log(isValid(')'));
```
전형적인 Parentheses 문제여서 쉽게 풀이했습니다.

하현숙 : leet 20 Valid Parentheses

---

hyeonsook95/baekjoon/15829.py
hyeonsook95/baekjoon/15829.ts

[문제 보러가기](https://www.acmicpc.net/problem/15829)
문제에서 주어진 조건과 수식을 구현하는 문제입니다.  
해당 문제를 Typescript로 풀다가 50점을 맞았습니다. small과 large가 나뉘어져 있었고, large 부분에서 전부 틀렸었습니다.
왜 large한 값들을 틀렸을까 생각해보다가 숫자의 범위와 관련 있는 문제이니 자료형의 문제일 것이라 생각했습니다. 그래서 똑같은 논리 구조를 파이썬으로 구현하였고, 모든 문제가 맞았습니다.
그리고 Typescript에서 쓸 수 있는 큰 숫자 자료형 `BigInt` 형을 찾아 문제를 해결하였습니다.
```typescript
const r = BigInt(31);
const M = BigInt(1234567891);
var L = parseInt(input[0]);
// 문자 해싱
var string = input[1].split('').map(char => BigInt(char.charCodeAt(0) - 96));
var amount = BigInt(0);
// 순서에 따라 다른 값이 나오도록 연산
for (var idx = BigInt(0); idx < L; idx++) {
amount += string[idx] * (r ** idx);
}
console.log(Number(amount % M));
```
js에서도 특정 숫자를 넘어가면 값이 변한다는 것을 …

하현숙 : boj 15829 Hashing

---

hyeonsook95/baekjoon/13015.py

[문제 보러가기](https://www.acmicpc.net/problem/13015)
그림을 그려 각 빈칸의 규칙성을 찾았습니다.
공통으로 만들어낼 수 있는 수식으로 `(N-2)*2+1` 를 찾아냈고, 이 수식을 기준으로 알고리즘을 만들었습니다.
패턴을 찾아내면 알고리즘이 단순해지기 때문에 별 모양의 패턴을 3가지로 축약하였고, 만들어낸 수식과 각 패턴들로 아래와 같은 알고리즘을 만들었습니다.
```python3
N = int(input())
size = (N - 2) * 2 + 1
border = "*" * N + " " * size + "*" * N
middle = "*" + " " * (N - 2) + "*" + " " * (N - 2) + "*"
inside = "*" + " " * (N - 2) + "*"
dump = 1
blank = -1
for h in range(size + 2):
blank += dump
if blank == 0:
print(border)
elif h == (size + 2) // 2:
print(" " * blank + middle)
dump = -1
else:
print((" " * blank) + inside + " " * (size - (blank * 2)) + inside)
```
변수의 이름이 적절하지 못한 것 같아 아쉽습니다. 좋은 아이디어 받습니다 😄

하현숙 : boj 13015 구현 별 찍기-23

---

hyeonsook95/baekjoon/9461.py
hyeonsook95/baekjoon/9461.ts

[문제 보러가기](https://www.acmicpc.net/problem/9461)
숫자 수열의 규칙을 찾는 문제였습니다. 각 수를 나열하고, 숫자가 만들어지는 수식을 기록하여 규칙을 찾았습니다.
```typescript
var P = [1, 1, 1, 2, 2]; // 수열을 저장할 어레이
const T = parseInt(input.shift());
for (var t = 0; t < T; t++) {
const n = input[t]; // 입력받은 수 n
// 이미 값을 구한 수는 다시 계산하지 않고, 어레이에 저장된 값을 출력합니다.
if (n < P.length + 1) {
console.log(P[n - 1]);
continue;
}
while (n != P.length) {
var idx = P.length - 1;
P.push(P[idx] + P[idx - 4]);
}
console.log(P[P.length - 1]);
}
```
리스트의 인덱스 개념이 정확하게 습득하지 않은 것 같습니다. 매번 디버깅으로 수정하네요!
인덱스 문제를 연습해야 할 것 같습니다.

하현숙 : boj 9461 구현 파도반 수열

---

lim8662/leetcode/leet-20.ts

[문제 보러가기](https://leetcode.com/problems/valid-parentheses/)
array를 스택으로 활용하여 풀었습니다.
문자열을 탐색하며 여는 괄호면 스택에 대응하는 닫는 괄호를 넣고
닫는 괄호면 pop하여서 같은지 확인합니다.
```typescript
function isValid(s: string): boolean {
let stack: string[] = [];
for (let i: number = 0; i < s.length; i++) {
switch (s.charAt(i)) {
case "(":
stack.push(")"); break;
case "{":
stack.push("}"); break;
case "[":
stack.push("]"); break;
default: {
if (s.charAt(i) !== stack.pop()) return false;
break;
}
}
}
if (stack.length > 0) return false;
return true;
};
```
전형적인 올바른 괄호 문제였습니다.

임영찬 : leet 20 Valid Parentheses

---

lim8662/boj/boj-13015.ts

[문제 보러가기](https://www.acmicpc.net/problem/13015)
도형의 맨 끝부분`edge`와 대칭이 되는 중앙`center`, 그리고 그 사이를 나누어서 그렸습니다.
사이는 규칙을 찾아 for문으로 구현하였습니다.
```typescript
const rl = require("readline").createInterface({
input: process.stdin,
output: process.stdout,
});
let input: string[] = [];
rl.on("line", function (line: string) {
input.push(line);
}).on("close", function () {
const N: number = parseInt(input.shift()!);
const B: number = N - 2; // 공백의 수
const BLANK: string = " ".repeat(B); // 공백 문자열
const edge: string = "*".repeat(N) + " ".repeat(B * 2 + 1) + "*".repeat(N);
const center: string = " ".repeat(N - 1) + "*" + BLANK + "*" + BLANK + "*\n";
let result: string = edge + "\n";
for (let i = 1, j = (B * 2 - 1); i <= B; i++, j-=2){
result += " ".repeat(i) + "*" + BLANK + "*" + " ".repeat(j) + "*" + BLANK …
```

임영찬 : boj 13015 구현 별 찍기-23

---

lim8662/boj/boj-15829.ts

[문제 보러가기](https://www.acmicpc.net/problem/15829)
모듈러 연산의 분배법칙을 이용해야 하는 문제입니다.
```typescript
const rl = require("readline").createInterface({
input: process.stdin,
output: process.stdout,
});
let input: string[] = [];
rl.on("line", function (line: string) {
input.push(line);
}).on("close", function () {
const L: number = parseInt(input.shift()!);
let answer = 0;
const M: number = 1234567891;
let r = 1;
for (let l = 0; l < L; l++) {
let a = input[0].charCodeAt(l) - 96;
// mod는 덧셈,곱셈 분배 법칙 성립
answer += (a * r) % M;
r = (r * 31) % M;
}
console.log(answer % M);
process.exit();
});
```
한 번에 100점이 아니라 아쉬웠습니다.

임영찬 : boj 15829 Hashing

---

edd0718/backjoon/15829.cpp

[문제 보러가기](https://www.acmicpc.net/problem/15829)
먼저, 수식을 구현해야하므로 r, M을 정의하였습니다.
r의 거듭제곱을 임시저장하기 위한 temp와 결과를 출력하기위한 res를 선언하였습니다.
수식을 그대로 표현하고자 아스키값을 내기 위한 코드를 포함해 간단히 구현하였습니다.
```cdouple
#define r 31
#define M 1234567891
int main() {
int l;
std::cin >> l;
std::string s;
std::cin >> s;
long long res = 0;
long long temp = 1;
for (int i=0; i<s.length(); i++) {
res += ((s[i]-'a'+1) * temp) % M;
temp *= r;
temp %= M;
}
std::cout << res % M << std::endl;
}
```
처음 문제를 보고, 수식이 주어져있어서 그대로 구현하면되겠다 생각했는데 잘 안되었습니다.
문자열의 길이 범위를 50까지로 예시를 주었고, 저 범위를 만족하는 자료형을 생각하는 것이 포인트였다고 생각합니다. 그리고 M으로 수식의 나머지를 계산하여 오버플로우를 방지하는 것도 중요하다고 생각했습니다.

code : junghwan boj 15829 datatype hashing

---

hyeonsook95/baekjoon/9095.py
hyeonsook95/baekjoon/9095.ts

[문제 보러가기](https://www.acmicpc.net/problem/9095)
`1, 2, 3` 이라는 제한된 숫자의 덧셈으로 한 숫자를 나타내는 `방법의 수`라는 문구를 보고 트리 형식의 dfs 구조를 떠올렸습니다. 그리고 중복된 패턴을 체크하지 않는다는 점에서 dfs 형식의 구조만 사용하면 되겠다고 생각했습니다.
저는 `dfs`를 주로 재귀 형식으로 구현하기 때문에 이 문제에서도 재귀로 구현하였습니다.
```typescript
var fs = require("fs");
const T = parseInt(input.shift());
function dfs(number, count) {
if (number == 0) {
return count + 1
}
for (var num of [1, 2, 3]) {
if (number >= num) {
count = dfs((number - num), count);
}
}
return count;
}
for (var t = 0; t < T; t++) {
var number = parseInt(input[t]);
console.log(dfs(number, 0));
}
```
간단한 dfs 문제였습니다. dfs 문제이기 때문에 stack으로도 구현할 수 있을 것 같습니다.
시간이 된다면 stack 형식으로 구현해보고 싶네요!

하현숙 : boj 9095 dfs 1,2,3 더하기

---

edd0718/backjoon/9461_2.cpp

[문제 보러가기](https://www.acmicpc.net/problem/9461)
P(1)-P(10)까지 10개의 숫자를 보면, 
P[4]=P[2]+P[1], P[5]=P[3]+P[2], ... , P[i]=P[i-2]+P[i-3]
에 대한 점화식을 유추할 수 있고 그대로 구현하였습니다.
``` cdouple
#include <iostream>
#define MAX 100
void dp() {
int n;
long long P[MAX];
std::cin >> n;
P[1] = P[2] = P[3] = 1;
for (int i=4; i<=n; i++) {
P[i] = P[i-2] + P[i-3];
}
std::cout << P[n] << std::endl;
}
int main() {
int t; // testcase
std::cin >> t;
for (int i=0; i<t; i++) {
dp();
}
}
```
long long 데이터타입!

이정환 : boj 9461 dp 파도반 수열

---

edd0718/backjoon/1913.cpp

[문제 보러가기](https://boj.kr/1913)
처음 이 문제를 보고 당황해서 전체 배열을 만들고, 
문제에 나와있는대로 하나씩 회전하도록 구현했습니다.
이러한 방법으로 구현하게되면 방향을 하나의 축이라고하였을때,
4개의 for문이 있어야하고 파라미터가 헷갈리게됩니다.
그래서 row와 column이 증가하는 구간과 감소하는 구간, 2부분으로만 나누어
key변수를 통해 값을 +/-로 방향을 바꾸는 방식으로 구현해보았습니다.
```cdouple
// boj 1913 - 달팽이
#include <iostream>
using namespace std;
int main() {
int x = 0, y = 0;
int key = 1;
int n, m, idx, idy;
std::cin >> n;
std::cin >> m;
int num = n*n;
int D[n][n];
for (int i=0; i<n; i++) {
for (int j=0; j<n; j++) {
D[i][j] = 0;
}
}
for (int k=0; k<n; k++) {
D[x][y] = num--;
x += key;
}
x -= 1;
for (int i=n-1; i>0; i--) {
for (int j=0; j<i; j++) {
y += key;
D[x][y] = num--;
}
key *= -1;
for (int k=0; k<i; k++) {
x += key;
D[x][y] = num--;
}
}
for (int i=0; i<n; i++) {
for (int j=0; j<n; j++) {
if (D[i][j] == m) {
idx = i+1; …
```

이정환 : boj 1913 달팽이

---

hyeonsook95/baekjoon/10798.py
hyeonsook95/baekjoon/10798.ts

[문제 보러가기](https://boj.kr/10798)
문제를 읽자마자 2차원 배열에 담은 후에 row별로 값을 가져오면 되겠구나 싶었습니다.
2차원 배열을 사용해서 풀 수도 있었지만, 제가 개인적으로 파이썬의 `zip()` 함수를 사용하는 것을 좋아해서 `zip`을 통해 풀어야겠다고 생각했습니다.
`zip`은 변수로 주어진 list를 index별로 짝지어서 튜플 형태로 반환하는 함수로 2차원 행렬을 역행렬할 때 유용하게 쓰일 수 있습니다.
```python3
chars = [input().strip().ljust(15) for _ in range(5)]
print("".join("".join(str) for str in list(zip(*chars))).replace(" ", ""))
```
`zip`을 사용해서 푸는 문제는 오랜만이라 재미있었습니다.

하현숙 : boj 10798 세로읽기

---

edd0718/backjoon/10025.cpp
edd0718/backjoon/10798.cpp

[문제 보러가기](https://boj.kr/10798)
이중 for문으로 row를 먼저 출력해주는 방식으로 구현했습니다.
```cdouple
// boj 10798 - 세로읽기
#include <iostream>
#include <string>
#include <vector>
using namespace std;
int main() {
vector<string> toy(5);
for (int i=0; i<5; i++) {
std::cin >> toy[i];
}
for (int i=0; i<15; i++) {
for (int j=0; j<5; j++) {
if (i<toy[j].size()) {
std::cout << toy[j][i];
}
}
}
return 0;
}
```
바로 출력해주면되는건데 새로운 벡터에 왜 담으려고했는지 모르겠음.

이정환 : boj 10798 세로읽기

---

sgh1939/baekjoon/2302.cpp

먼저 좌석이 1~ 5개 일 때를 직접 구해봤습니다. 
그리고 VIP 좌석을 기준으로 나눠서 보니까
1 2 3 **4** 5 6 **7** 8 9
좌석에서 VIP가 4, 7 일 때,
[1 2 3], [5, 6], [8, 9]
이고 3개, 2개, 2개인 걸 보고 각 가짓수의 값을 곱하면 전체 가짓수가 나올 것 같아서 곱했더니 12가 나온 걸 보고
맞다는 걸 확인 했습니다.
이제 가짓수의 값을 구하는 함수를 구현하면 끝나겠다 싶어서 가짓수의 증가에 따른 규칙을 찾으려고 보니
dp[n] = dp[n-1] + dp[n-2] 인 걸 확인했고 DP를 함수로 구현 했습니다.

규환 백준 2302 dp 극장좌석

---

hyeonsook95/baekjoon/11726.py
hyeonsook95/baekjoon/11726.ts

[문제 보러가기](https://boj.kr/11726)
이전에 풀었던 문제였어서 dp였다는 힌트를 알고 시작한 상태였습니다.
dp는 점화식을 사용하여 문제를 해결하는 알고리즘 방식이었기 때문에 1차례의 루프가 돌 때마다 어떤 점화식이 나오는지 확인해봐야겠다고 생각했습니다.
n을 1부터 시작하여 +1씩 해나가면서 2*n개의 타일을 만들 수 있는 가짓수를 표시하였고, `dp[n] = dp[n-2] + dp[n-1]` 이라는 점화식을 구해낼 수 있었습니다.
일반적으로 dp 에서 2이하의 dp는 점화식이 성립하지 않기 때문에 `dp = [0, 1, 2]`로 dp의 값을 저장하는 리스트를 선언하고 시작하였습니다.
```python3
dp = [0, 1, 2]
```
남은 부분은 입력으로 주어진 `N` 번째까지 점화식을 사용하여 계산하는 부분입니다. `N` 까지라는 종료 조건이 있어, 문제에서 주어진 상황에 맞게 `while` 문으로 간단히 돌렸습니다.
```python3
while N > len(dp) - 1:
dp.append((dp[-1] + dp[-2]) % 10007)
```
문제가 풀리지 않을 때 dp로 접근하는 연습을 해야 할 것 같습니다.

하현숙 : boj 11726 2*n 타일링

---

kha/boj/11726.py

그나마 DP 문제 중에서 쉽게 점화식을 떠올릴 수 있었던 케이스였던 것 같음

김현아 : 백준 11726 2xn 타일링

---

kha/boj/2302.py

자리를 교환해야 하는 횟수를 한 번에 구하려는 생각보다 
조건을 통해 범위를 좁혀나가며 답을 구하는 사고방식이 필요했음

김현아 : 백준 2302 극장좌석

---

sgh1939/baekjoon/11726.cpp

이전 문제인 극장 좌석을 풀었을 때, 9의 값을 넣고 55가 나왔었는데.  
문제 예시에 같은 값이 나오는 걸 보고 이전 문제에 코드를 고대로 가져와서 조금 수정 했습니다.
문제를 봐도 좌석 옮기는 거랑 같은 방법이고 다만 범위의 차이가 있는 걸로 보였습니다.
나중에 나오는 값에 10007로 나눈 나머지로 했더니 틀렸다고 나와서 중간에 아예 10007로 나눈 값을 넣었더니 맞았습니다.

규환 백준 11726 dp 2xn 타일링

---

hyeonsook95/baekjoon/15591.py

[문제 보러가기](https://boj.kr/15591)
1. 선언부
```typescript
const map = new Map([
['2', ['a', 'b', 'c']],
['3', ['d', 'e', 'f']],
['4', ['g', 'h', 'i']],
['5', ['j', 'k', 'l']],
['6', ['m', 'n', 'o']],
['7', ['p', 'q', 'r','s']],
['8', ['t', 'u', 'v']],
['9', ['w', 'x', 'y', 'z']] 
]);
let answer: string[] = []; 
```
입력받은 숫자에 대응하는 문자들을 Map에 저장해두었습니다.
그리고 반환할 정답 배열을 선언하고 빈 배열로 초기화하였습니다.
2. 구현부
```typescript
function letterCombinations(digits: string): string[] {
answer.length = 0; // 정답 배열 초기화
// 입력받은 숫자가 있으면 모든 문자 조합을 구함
if(digits.length) comb(digits, 0, '');  
return answer;
}
// 재귀로 조합 구현
function comb(digits: string, idx: number, str: string) {
if (idx === digits.length) { // 문자 조합이 완성되면 정답 배열에 추가
answer.push(str);
return;
}
// 현재 숫자로 가능한 문자 배열 읽어옴
const charArr: string[] | undefined = …
```

하현숙 : BOJ 15591 MooTube

---

ilhoon93/boj/boj-11726.py
ilhoon93/boj/boj-2302.py

오래전에 한번 풀었던 문제로 DP문제라는 것은 파악하고 있었습니다. n = 1부터 n을 증가시켜 나가며 동일한 패턴의 타일이 반복되는 것을 그려가며 패턴을 파악했습니다. 
패턴을 두가지로 나눠보면 첫번째 막대기를 세로로 놓는 경우와 가로로 놓는 경우로 분류할 수 있습니다. 예를 들어 n이 5일 때, 첫번째 막대기를 세로로 세우면 첫번째를 제외한 나머지는 n*4 크기의 타일을 채우는 경우와 같습니다. 첫번째를 가로로 세운다면 나머지는 n  * 3 크기의 타일을 세우는 경우과 같습니다. 따라서 dp[5]의 답은 dp[4] + dp[3]과 같습니다.
인덱스 0과 1을 1로 초기화 하고 인덱스 2번부터 n+1만큼 반복하며 타일을 채우는 방법의 수를 구합니다. 아이디어만 떠올린다면 구현상의 어려움은 없었습니다.

강일훈 : boj 11726 dp 2*n타일링

---

ilhoon93/boj/boj-2302.py

n = 1부터 n = 4까지 하나씩 그림을 그려보며 패턴을 파악했습니다. 똑같은 패턴이 반복되는 것은 파악했지만 DP유형 문제를 많이 풀어보지 않아서 점화식으로 표현하는데 어려움을 겪었습니다. 
VIP좌석들의 번호를 배열로 저장하였고, 각 좌석의 개수별로 앉을 수 있는 경우의 수를 담은 배열을 초기화하고 인덱스 0, 1의 값은 1로 세팅해주었습니다. 
처음부터 끝까지 vip 좌석 사이 사이 마다 연속된 좌석들의 개수를 구하고, 그 숫자만큼 앉을 수 있는 경우의 수들을 곱해 결과값을 도출하였습니다.
m이 0인 경우를 처음에 고려하지 않아 인덱스 오류가 발생했습니다.
DP 패턴을 파악하여 점화식을 도출하는 과정에서  앞의 자리 혹은 앞앞 자리의 값이 공통된 것으로 묶어서 확인해보는 것이 유용한 것 같습니다.

강일훈 : boj 2302 dp 극장좌석

---

kha/programmers/68645.py

문제링크: https://programmers.co.kr/learn/courses/30/lessons/68645?language=python3
규칙성을 이용해서 풀음
다만 이렇게 풀면 할당한 2차원 배열의 반은 안쓰게돼서 더 깔끔하게 푸는 방법을 고민하면 좋을 것 같음

김현아 : 프로그래머스 68645 삼각 달팽이

---

kha/boj/2437.py

문제링크: https://www.acmicpc.net/problem/2437
처음에는 합분해 DP 방식으로 풀다가, 같은 무게의 추가 중복해서 있을 수 있다는 조건이 있어서 다른 방식으로 알고리즘을 변경함
어떤 알고리즘으로 풀지 오래 고민했던 문제

김현아 : 백준 2437 저울

---

kha/boj/2493.py

문제링크: https://www.acmicpc.net/problem/2493
시간 복잡도 계산하는게 익숙하지 않아서 스킵했다가 오답처리 된 문제
문제를 풀 때 주어진 시간이나 메모리 용량에 비해 값 범위가 작지 않다면 시간 or 메모리 초과 케이스를 고려해 봐야 함

김현아 : 백준 2493 탑

---

kha/boj/1246.py

문제링크: https://www.acmicpc.net/problem/1246 
어렵지 않게 알고리즘을 떠올릴 수 있었던 문제
구매하고자 하는 사람이 달걀 개수보다 많은 경우를 따로 처리하지 않아서 한 번 틀렸었음
예외 상황을 좀 더 꼼꼼하게 보는 습관이 필요할 듯

김현아 : 백준 1246 온라인 판매

---

sgh1939/baekjoon/1246.cpp

먼저 vector<int> v 에 내림차순으로 정렬 합니다.
그리고 달걀 개수만큼만 판매할 수 있고 내림차순으로 정렬된 배열에 제일 첫 번째부터
순서대로 cnt = 1, (cnt++) 값을 곱해서 가장 큰 금액이 나올 때까지 갱신해줍니다.
예를 들어 예제 값을 내림차순으로 정렬하면 10, 8, 7, 2 으로 정렬됩니다.
N만큼
1. 10 * 1 = 10 
2.  8 * 2 = 16
3. 7 * 3 = 21
4. 2 * 4 =8
을 해서 가장 큰 값을 구합니다. 7 21

심규환 boj  1246 온라인 판매

---

sgh1939/baekjoon/2493.cpp

입력을 받고 처리를 하면 시간 초과가 될 것 같아서 받으면서 처리할 수 있도록 구현했습니다.
먼저 타워 값과 인덱스 값을 담을 구조체를 생성했습니다.
문제의 분류를 보니 스택이라고 적혀있어서 스택을 사용했습니다.
제일 처음 타워는 송신할 타워가 없기 때문에 결과를 반환할 배열에 0을 넣어줬고 스택에 첫 타워 높이와 인덱스를 넣어주고 시작했습니다.
그 후부터는 탑의 높이 값을 받으며 스택에 제일 위에 있는 값과 비교해서 같거나 큰 값이 없으면 스택에서 빼고 비어있으면 0을 넣어주고 만약 큰 값이 있으면 결과 배열(result)와 스택에 넣어주고 
결과 배열을 반환해주면 끝납니다.

심규환 boj 2493 탑

---

sgh1939/baekjoon/2437.cpp

먼저 추들의 값을 정렬한 뒤, 제일 최솟값 1을 res에 넣고 시작합니다.
추 값의 제일 작은 값부터 시작해서 res 값보다 크면 break 해줍니다. 예를 들어 res가 1인데, 추가 2부터 시작되면 바로 break 해주고 측정할 수 없는 최솟값은 1이 됩니다.
만약 크지 않으면 res에 더해줍니다. 이를 반복하면 최솟값이 나옵니다.

심규환 boj 2437 저울

---

sgh1939/programmers/삼각달팽이.cpp

정수 n일 때의 최대 값을 dp(n)이라 했을 때, dp(n) = dp(n-1) + n 이어서 이를 dp로 풀었습니다. 
다 풀고 보니 자연수 거듭제곱의 합이어서 n(n+1)/2 로 바로 구할 수 있다는 걸 알았는데. 따로 수정하지는 않았습니다.
n이 4일 때
1
2 9
3 10 8
4 5 6 7 
값인데. 이를 동적배열 tmp[4]에 
tmp[1] : 1
tmp[2] : 2 9
tmp[3] : 3 10 8
tmp[4] : 4 5 6 7
을 넣어주고 하나로 합치면 되겠다 싶어서 규칙을 찾아봤습니다.
세 가지 패턴이 반복되는데, count를 1로 넣고 N개 만큼 넣어줍니다. N은 -1 씩 줄어듭니다. 
첫 번째 패턴은 tmp[1] ~tmp[N] 에 count++ 값을 하나씩 넣어줍니다. N--
두 번째 패턴은 tmp[N] 에 N-1 개수만큼 count++를 해서 넣어줍니다. N--
세 번째 패턴은 tmp[N-1] ~tmp[N-(N-1)) 만큼 count++를 넣어줍니다. N--
설명을 잘 못했는데. 이렇게 패턴을 찾은 다음 구현하기 위해, 두 가지 front, back 동적배열을 생성했습니다.
예를 들어, 위의 N이 5일 때,
첫 번째 패턴 :
N = 5 
Front[1] = 1
Front[2] = 2
Front[3] = 3
Front[4] = 4
Front[5] = 5
N--
두 번째 패턴 :
N = 4 
Front[5] = 5,6
Front[5] = 5,6,7 
Front[5] = 5,6,7,8
Front[5] = 5,6,7,8,9
N--
세 번째 패턴 : (이 값을 Back[N] 값에 따로 …

심규환 programers 68645 삼각당팽이

---

hyeonsook95/baekjoon/1246.py

[문제 보러가기](https://boj.kr/1246)
숫자의 범위도 적었고, 1사람당 1개의 달걀을 판다는 제한 조건이 있었기 때문에 N번째 까지의 경우의 수를 계산하고 가장 큰 값을 출력하면 되겠다고 생각했습니다.
```python3
for idx, p in enumerate(P[:N]):
if amount < (idx + 1) * p:
price = p
amount = (idx + 1) * p
```
깊이 생각하지 않고, 그냥 풀었던 것 같습니다. 나중에 시간이 된다면 다른 방법으로 풀어보고 싶네요 😄

하현숙 boj 1246 온라인판매

---

hyeonsook95/baekjoon/2493.py

[문제 보러가기](https://boj.kr/2493)
레이저의 방향이 왼쪽으로 정해져 있고, 현재 탑의 높이보다 큰 단 하나의 값만 찾으면 되기 때문에 한쪽으로 입/출력을 하고 top 값이 의미를 갖는 스택을 사용해야겠다고 생각했습니다.
```python3
for idx, top in tops:
while stack and stack[-1][-1] <= top:
stack.pop()
stack.append((idx, top))
answer.append(stack[-1][0] if stack else 0)
```
매 루프마다 stack을 현재 탑까지의 tops로 채우니 시간초과가 났습니다.
불필요한 연산을 줄이도록 노력해야겠다고 생각했습니다.

하현숙 boj 2493 탑

---

ilhoon93/boj/boj-2437.py

처음엔 모든 조합을 구해서 찾는 알고리즘을 떠올렸지만, 시간초과로 실패하고 좀 더 효율적인 알고리즘을 찾았다. 무게 w를 측정할 수 있는 추들의 집합에 새로운 추 x가 되면 x부터 x+w구간 까지는 모두 측정이 가능하다는 규칙을 이용했다. 추들을 무게 순으로 오름차순 정렬하고 새롭게 추가되는 x와 현재까지 추들로 표현가능한 w를 비교한다. 새롭게 추가되는 x가 w보다 크다면 w와 x 사이에 무게는 측정이 불가능하다. 따라서 이때 w+1을 출력하면 측정 불가능한 최소값을 구할 수 있다.
구현상 특이 점은 없었다.
알고리즘의 아이디어를 떠올리는게 어려웠다..

강일훈 : boj 2437 저울

---

ilhoon93/boj/boj-2493.py

2개의 for문으로 구현하려했던 첫번째 방법은 시간초과로 실패!
현재 탑보다 더 높은 첫번째 왼쪽탑의 위치만 알면 되기때문에 스택의 맨 위에 해당 값을 저장해놓고 비교하는 방식으로 구현하였다.
현재 탑의 높이와 스택에 저장된 높이를 비교해서 현재 탑의 높이보다 작거나 같은 것들은 모두 제거한다. 이때 남은 스택에 맨위값이 레이저를 맞는 첫번째 탑이다. 결과 배열에 인덱스을 추가한다.
만약 스택에 아무것도 없다면? 왼쪽에 현재 탑보다 높은 탑이 하나도 없는 것이므로 0을 저장한다. 
현재 탑의 높이가 더 작다면 그대로 스택에 저장한다.
파이썬 배열의 append와 pop을 이용하여 스택처럼 사용하였고, 인덱스와 값을 같이 알아야하기 때문에 튜플 자료형을 사용했다.
스택을 이용한 방법이 바로 떠오르지 않아서 인터넷을 보고 힌트를 얻었다ㅠ

강일훈 : boj 2493 탑

---

kha/boj/16506.py

문제링크: https://www.acmicpc.net/problem/16506
명령어별로 동작이 조금씩 달라서 어떻게 묶을지 고민했던 문제
구체적인 포매팅은 처음 써봤는데 코드를 간결하게 하는데에 좋은듯

code : 김현아 백준 16506 구현 CPU

---

kha/boj/11559.py

문제링크: https://www.acmicpc.net/problem/11559
이전에 한번 풀었었어서 어렵지 않게 풀었음
뿌요를 터트리면 아래로 다른 뿌요들이 내려와야해서 그 부분의 구현이 복잡할거같아 조금 고민이었는데,
전치로 만드니까 삭제되는 뿌요와 내려오는 뿌요가 같은 행에 있어서 구현하기 좀 더 편했던 것 같음

김현아 : 백준 11559 Puyo Puyo

---

kha/programmers/12981.py

문제링크: https://programmers.co.kr/learn/courses/30/lessons/12981
큰 어려움 없이 무난하게 풀었던 문제

김현아 : 프로그래머스 12981 영어 끝말잇기

---

kha/leetcode/55.py

문제링크: https://leetcode.com/problems/jump-game/submissions/
그리디를 사용해서 무난하게 풀었던 문제

김현아 : leetcode 55 Jump Game

---

raquelkim/16506.py

```python3
import sys
n = int(sys.stdin.readline())
assem = [list(input().split()) for _ in range(n)]
code = {'ADD' : 0, 'SUB' : 1, 'MOV' : 2, \
'AND' : 3, 'OR' : 4, 'NOT' : 5, 'MULT' : 6, \
'LSFTL' : 7, 'LSFTR' : 8, 'ASFTR' : 9,\
'RL' : 10, 'RR' : 11 }
result = []
for op, rd, ra, rb in assem:
sen = ""
if op[-1] == "C":
sen += bin(code[op[:-1]])[2:].zfill(4)
sen += "10"
else:
sen += bin(code[op])[2:].zfill(4)
sen += "00" 
sen += bin(int(rd))[2:].zfill(3)
sen += bin(int(ra))[2:].zfill(3)
if op[-1] == "C":
sen += bin(int(rb))[2:].zfill(4)
else:
sen += bin(int(rb))[2:].zfill(3)
sen += "0"
result.append(sen)
for i in range(n):
print(result[i])
```

김진경 boj 16506 구현

---

raquelkim/jumpgame.py

```python3
class Solution:
def canJump(self, nums) -> bool:
location = 0
for i in range(len(nums)):
location += nums[i]
if location == len(nums):
return True
elif location > len(nums):
return False
```

김진경 let jump game

---

raquelkim/wordchaingame.py

```python3
def solution(n, words):
visited = [words[0]]
for i in range(1, len(words)):
if len(words[i]) > 1:
if words[i-1][-1] != words[i][0] or words[i] in visited:
return [(i%n)+1, (i//n)+1]
else:
visited.append(words[i])
else:
return [(i%n)+1, (i//n)+1]
return [0,0] 
```

김진경 pro 구현 wordchaingame

---

hyeonsook95/leetcode/55.py

[문제 보러가기](https://leetcode.com/problems/jump-game/)
](https://leetcode.com/problems/jump-game/discuss/596454/Python-Simple-solution-with-thinking-process-Runtime-O(n)) 를 보고 풀이를 이해한 후 코드를 작성하였습니다.
해당 풀이의 핵심 아이디어는 `idx+nums[idx] >= last_position` 입니다.
마지막 인덱스의 값에 도달할 수 있는지를 물어보는 문제이므로, 마지막 인덱스에서 출발하여 매번 해당 아이디어인 `idx+nums[idx] >= last_position` 값이 유효한지 확인하고, 유효할 경우 인덱스 값을 업데이트 시켜줍니다.
그리고 모든 인덱스를 확인했을 때, 마지막으로 업데이트된 값이 0이면 문제의 조건을 출력했음을 알 수 있습니다.
문제를 못..풀었습니다.. 😔
그래서 다른 분들의 풀이법을 몇 개 확인하고 흥미롭고 재미있는 풀이를 익히고 풀어보았습니다.

하현숙 : let 55 Jump Game

---

hyeonsook95/programers/12981.py

[문제 보러가기](https://programmers.co.kr/learn/courses/30/lessons/12981)
1. 선언부
```python3
turns = [[] for _ in range(n)] # n번째 사람이 말한 단어를 저장
dictionary = defaultdict(int) # 끝말잇기에서 나온 단어를 저장
prev = words[0][0] # 이전에 말했던 단어를 저장
```
2. 구현부
```python3
for idx, word in enumerate(words):
if prev[-1] != word[0] or dictionary[word]:
return [(idx % n) + 1, len(turns[idx % n]) + 1]
turns[idx % n].append(word)
dictionary[word] += 1
prev = word
return [0, 0]
```
n 번째 사람이 몇 번째 단어를 말했을 때, 탈락했을지를 구하는 부분에서 고민이 많았었습니다.
따로 저장하지 않고 나눗셈 연산으로 풀 수 있을 것 같은데, 다음에 고민해봐야겠습니다.

하현숙 : pro 12981 구현 영어끝말잇기

---

hyeonsook95/baekjoon/16506.py

[문제 보러가기](https://boj.kr/16505)
명령어에 C가 붙느냐에 따라 연산이 조금 달라지는 부분에 신경써서 구현했습니다.
```python3
if opcode[-1] == "C":
opcode = opcode[:-1]
b_opcode = "1"
b_rB = bin(int(rB))[2:].rjust(4, "0")
```
간단한 구현문제였습니다.

하현숙 : boj 16506 CPU

---

sgh1939/baekjoon/16506.cpp

**map<string, pair<int, int>> m** ====> map<**어셈블리 코드, pair<opcode(10진수), _4bit 값_**>> 으로 초기화 해줍니다.
그리고 4비트 생성 함수, 3비트 생성 함수를 따로 만듭니다. 
```c++
string threeBitCreate(int num){
string result ="";
bitset<3> bs(num);
return result = bs.to_string();
}
string fourBitCreate(int num){
string result ="";
bitset<4> bs(num);
return result = bs.to_string();	
}
```
그 후는 설명 순서대로 생성하고 _4bit 값_을 기준으로 0일 때는 레지스터 rB를 1일 경우 상수 #C를 사용한다고 정의된 것 처럼 이를 처리합니다. 
```c++
if(isC == 0){
// 3bit
result.push_back(threeBitCreate(stoi(v[3])));
// 1bit
result.push_back(zero);
}else{
// 4bit
result.push_back(fourBitCreate(stoi(v[3])));
}
```
그리고 결과 값을 반환해줍니다.

심규환 baekjoon 16506 CPU

---

sgh1939/programmers/영어 끝말잇기.cpp

심규환 programmers 영어 끝말잇기

---

sgh1939/baekjoon/11559.cpp
sgh1939/leetcode/53. Jump Game.cpp

DFS 를 사용해서 풀었습니다. 
DFS를 사용해서 **현재 같은 색상**이고 **붙어있고** **방문하지 않은 곳**이면 vector에 해당 색상의 좌표 값을 모조리 담아 줍니다.
담긴 값이 4개 이상이면 이 vector를 담을 vector2에다가 추가 해줍니다. 
이렇게 1회 게임이 종료되면 vector2에는 4개 이상인 친구들의 좌표가 담겨집니다. 
이 좌표에 있는 친구들의 색상을 '.'로 모두 바꿔주고 중력함수를 구현해서 모두 아래로 내려줍니다.  이때 터트린 횟수를 +1 해주고 
이를 반복해주면 끄읏

심규환 baekjoon 11559 puyo puyo

---

kha/boj/16506.py

문제링크: https://www.acmicpc.net/problem/16506
명령어별로 동작이 조금씩 달라서 어떻게 묶을지 고민했던 문제
구체적인 포매팅은 처음 써봤는데 코드를 간결하게 하는데에 좋은듯

김현아 : 백준 16506 CPU

---

ilhoon93/boj/boj-11559.py

`.` 이 아닌 데이터를 만나면 dfs로 같은 문자들을 찾는다. 
4개 이상 연속되어 있으면 해당 문자들을 `.`으로 초기화한다. 모든 인덱스를 돌면서 반복한다.
4개 이상 연속되어 변경된 것이 있으면 연쇄 횟수를 1증가시킨다. 
변경된 데이터 중 `.` 위쪽에 문자가 있으면 문자들을 맨 아래로 당긴다. 
이후 같은 로직을 반복 수행하다가 하나도 지우지 못하면 프로그램을 종료하고 연쇄 횟수를 반환한다.
풀면서 먼가 답답하지만 그냥 넘어갔던 부분 다시 한번 보면서 찾아보장
- 연속된 문자의 개수를 전역변수를 사용하지 않고 계산하는 방법
- 4개 이상 연속되었는지 판단하는 `dfs` 함수와 연속된 것들을 터트리는 `bomb`함수에 코드 중복을 줄이는 방법

강일훈 : boj 11559 Puyo Puyo

---

ilhoon93/programmers/programmer-영어끝말잇기.py

https://programmers.co.kr/learn/courses/30/lessons/12981
단어를 하나씩 확인하며 이전에 사용한 단어인지, 끝말이 이어지는지, 한글자인지 3가지를 검증해야한다. 
빠르게 조회할수 있도록 딕셔너리를 만들어 이전에 사용한 단어인지 확인하였다. 그리고 각 사람이 사용한 끝말만 저장하는 배열을 만들어 현재 단어의 첫글자와 이전 사람의 마지막 글자를 비교했다. 
현재 인덱스을 사람 숫자로 나눈 나머지가 0이라면 한바퀴 돈 것으로 볼수 있기때문에 이때 차례를 증가시켜준다.
defaultdict를 사용해서 키가 없을때 바로 입력될수있게했다. i%n을 활용해 각 단어에 할당되는 사람을 구했다.

강일훈 : programmers 영어끝말잇기

---

ilhoon93/leet/leet-55.py

https://leetcode.com/problems/jump-game/
0부터 n-1까지 현재 인덱스에서 마지막 인덱스로 갈 수 있는지 여부를 확인했다.
이때 몇가지 예외처리를 해줘야 한다. 먼저 길이가 1이면 무조건 True이다. 그리고 현재 값이 0인 경우 이전 값들을 하나씩 확인하며 0이 아닌 값으로 점프할수 있는지 판단한다. 
0이 연속될 경우 불필요한 연산을 줄이기위해 가장 마지막 0으로 이동하여 그때만 반복문을 타도록 했다.
nums[i] + i >= n -1을 만족한다면 현재 인덱스에서 마지막으로 점프할수있다
nums[r] + r >= i+1을 만족한다면 마지막 0인덱스 뒤로 점프할수있다.
중간에 0을 처리하는 부분이 생각보다 시간이 오래걸렸다

강일훈 : leetcode 55 jump game

---

kha/leetcode/14.py

문제링크: https://leetcode.com/problems/longest-common-prefix/

김현아 : leetcode 14 Longest Common Prefix

---

ilhoon93/boj/boj-1012.py

https://www.acmicpc.net/problem/1012
dfs를 사용해서 구현했다. 배추밭 데이터와 방문여부를 체크하는 배열을 테스트 케이스마다 초기화하고, 모든 요소를 방문하면서 dfs를 수행한다. dfs를 한번 수행할 때마다 인접한 요소를 모두 방문하고, cnt를 1씩 증가시킨다.

강일훈 : boj 1000 유기농 배추

---

raquelkim/SNP.py

1. 선언부
시작점을 기억하는 root
head 는 현재 노트
prev 는 head의 이전
b는 head의 이후 
2. 구현부
head가 None 값이 아닐때까지 while 문을 돌면서 
b에  head의 다음 값을 넣어주고
head는 b의 next를 가리키게 하고
b의 연결리스트 방향을 head를 향하게 바꿔준다.
그다음 prev의 next 가 b를 가리키게 하고
head 는 앞으로 이동을 하고
prev도 b의 앞으로 이동하게 한다. 
연결리스트를 너무 오랜만에 풀어서 기억이 나질 않아서 초반에 이해하는데 시간이 많이 걸렸습니다.
더 연습이 필요할 것 같습니다.

code : 김진경 leetcode swapPairs linkedList

---

raquelkim/1012.py

[문제 보러가기](https://www.acmicpc.net/problem/1012)
1. 선언부
입력 받은 x, y 좌표는 field 라는 2차원 배열에 넣었습니다. 
2. 구현부
1인 칸을 발견하면 BFS 함수를 호출하고, 그 구역의 1은 0으로 바꿉니다. 
1인 칸을 발견할 때마다 cnt +1 을 합니다. 
BFS 함수 부분에서는 따로 리턴값이 없습니다. 
아직은 알고리즘에 대한 두려움이 있는데, 쉽게 접근 가능한 BFS 문제라서 이해를 높이고 두려움을 낮출 수 있었습니다.

code : 김진경 boj 1012 유기농배추

---

hyeonsook95/baekjoon/1012.py

[문제 보러가기](https://boj.kr/1012)
배추가 존재할 경우, bfs 로 배추벌레가 먹을 수 있는 범위를 체크했습니다. 배추벌레가 먹을 수 있는 지역을 탐색하기 전에 배추벌레를 카운트해서 총 필요한 벌레의 개수를 구했습니다.
```python3
def bfs(start_v):
q = deque([start_v])
visited[start_v[0]][start_v[1]] = True
while q:
v = q.popleft()
for d in range(4):
if (
-1 < v[0] + dr[d] < N
and -1 < v[1] + dc[d] < M
and maps[v[0] + dr[d]][v[1] + dc[d]]
and not visited[v[0] + dr[d]][v[1] + dc[d]]
):
q.append((v[0] + dr[d], v[1] + dc[d]))
visited[v[0] + dr[d]][v[1] + dc[d]] = True
```
bfs 를 이용한 간단한 알고리즘 이었습니다.

하현숙 : boj 1012 bfs 유기농 배추

---

kha/boj/17140.py

문제링크: https://www.acmicpc.net/problem/17140

김현아 : 백준 17140 이차원 배열과 연산

---

hyeonsook95/programers/81302.py

[문제 보러가기](https://programmers.co.kr/learn/courses/30/lessons/81302)
주어진 place에서 `P`가 발견되면 `P`를 중심으로 탐색을 시작했습니다.
```python3
visited = [[False for _ in range(5)] for _ in range(5)]
for r in range(5):
for c in range(5):
if not visited[r][c] and place[r][c] == "P":
if not search(r, c):
```
해당 `P`의 좌표를 시작으로 하여 다음 탐색할 좌표를 queue에 담도록 했습니다.
다음 탐색할 좌표를 담기 전에 이전에 탐색한 위치와 맨허튼 거리를 계산하여 2 이상의 좌표는 담지 않도록 했습니다.
그리고 해당 좌표가 맨허튼 거리 내이면 파티션의 유무와 사람의 유무를 판단하도록 하였습니다. 파티션이 있다면 탐색하지 않아도 되기 때문에 `visited`만 표시하고 queue에 담지 않았습니다.
그리고 사람이 있으면 바로 탐색을 종료하고, 해당 place에 0을 입력했습니다.
```python3
dr = [-1, 1, 0, 0]
dc = [0, 0, -1, 1]
def search(sr, sc):
visited[sr][sc] = True
queue = [(sr, sc)]
while queue:
vr, vc = queue.pop()
for d in range(4):
wr, wc = vr + dr[d], vc + dc[d]
dist = abs(sr - wr) + abs(sc - wc)
if -1 < wr < …
```

하현숙 pro 81302 구현 거리두기 확인하기

---

kha/boj/14719.py

문제링크: https://www.acmicpc.net/problem/14719

김현아 : 백준 14719 빗물

---

ilhoon93/leet/leet-14.py

https://leetcode.com/problems/longest-common-prefix/
문자열들 중 가장 길이가 작은 문자열의 길이를 구한다. 구한 길이만큼 루프를 돌면서 해당 인덱스 문자를 비교한다. 해당 인덱스의 문자가 모두 같으면 결과 문자열에 추가하고 다르면 프로그램을 종료한다.

강일훈 : leet 14 Longest Commom Prefix

---

kha/leetcode/24.py

문제링크: https://leetcode.com/problems/swap-nodes-in-pairs/
Linked List의 특징을 이용해서 풀었던 문제
다른 곳에서 쉽게 보지 못했던 문제 유형이라 신기했음

김현아 : leetcode 24 Swap Nodes in Pairs

---

kha/boj/9205.py

문제링크: https://www.acmicpc.net/problem/9205

김현아 : 백준 9205 맥주 마시면서 걸어가기

---

kha/boj/12761.py

문제링크: https://www.acmicpc.net/problem/12761

code : 김현아 백준 12761 BFS 돌다리

---

raquelkim/12761.py

[문제 보러가기](https://www.acmicpc.net/problem/12761)
1. 선언부
```typescript
a, b, n, m = map(int, input().split())
s = [0 for i in range(100001)]
입력받은 변수를 map으로 int 형 변환을 해주었고, 공백을 기준으로 나누었습니다. 
이전까지 왔던 경로 수를 기억하기 위해 s 라는 이름으로 리스트를 만들어주었습니다. 
2. 구현부
```typescript
while queue:
x = queue.popleft()
for i in range(8):
if i < 6:
nx = x + d[i]
if 0 <= nx <= 100000 and visit[nx] == 0:
queue.append(nx)
bfs 로 구현 했습니다. 8가지의 경우의 수 중 앞 6개는 덧셈으로 진행하고, 나머지는 곱셈으로 진행하기 때문에 if 로 조건을 나누었습니다. 
방문하지 않았고, 범위를 넘어가지 않는다면 queue에 넣어주고, 방문처리하고, 이전까지 왔던 방법의 수 + 1 을 해주어 s 에 넣어주도록 했습니다. 
bfs 로 해야 할 줄 모르고, 아예 감을 못 잡아서 다른 분들의 해결 방법을 참고 했습니다. 
부족한 제 실력을 다시 느낄 수 있었습니다...

code : 김진경 boj 12761 돌다리

---

hyeonsook95/baekjoon/9205.py

[문제 보러가기](https://boj.kr/9205)
```python3
import sys
input = sys.stdin.readline
MAX_BEER_CNT = 20
def solution():
N = int(input().strip())
postions = [(map(int, input().strip().split())) for _ in range(N + 2)]
dist = 0
pre_x, pre_y = postions[0]
for cur_x, cur_y in postions[1:]:
dist += abs(pre_x - cur_x) + abs(pre_y - cur_y)
drunk, dist = divmod(dist, 50)
pre_x, pre_y = cur_x, cur_y
if MAX_BEER_CNT - drunk < 0:
return "sad"
return "happy"
T = int(input().strip())
for _ in range(T):
print(solution())
```
틀렸습니다. `상근이는 모든 편의점을 방문하지 않아도 된다.` 와 같은 예외 상황을 생각하지 못했습니다. 알고리즘 풀 때 좀 더 깊이 있게 생각하는 연습을 해야할 것 같습니다.
이건 다음에 다시 풀어봐야겠네요.

하현숙 boj 9205 맥주 마시면서 걸어가기

---

hyeonsook95/programers/150370.py

[문제 보러가기](https://school.programmers.co.kr/learn/courses/30/lessons/150370)
약관의 종류를 확인하고 해당 유효기간을 더한 후 오늘 날짜와 비교하면 되는 단순한 로직이었기 때문에 주어진 개인 정보 약관 리스트를 순차적으로 확인하여, 파기해야 할 문서의 인덱스를 리스트에 저장하는 방법을 사용해야겠다고 생각했습니다.
계산을 쉽게 하기 위해 주어진 약관의 값을 가공했습니다.
```python3
dt = {k: int(v) for k, v in map(lambda t: t.split(' '), terms)}
```
약관의 유효기간의 단위는 **달** 이어서 달과 년의 계산 로직이 중요했습니다.
12달이 넘게 되면 1년이 되고, 달은 1월로 초기화되므로 각각 나눗셈 연산과 나머지 연산으로 새로운 년과 월을 계산했습니다.
```python3
dm = m + dt[t]
y += dm // 12
m = dm % 12
```
계산한 dm 값이 12의 배수일 경우, m 값은 0이 됩니다. 해당 경우를 처리하기 위해 조건을 추가했습니다.
```
if m == 0:
y -= 1
m = 12
```
계산식을 좀 더 간결하게 사용할 수 있을 것 같은데 아이디어가 나오지 않아 아쉽습니다. 
나머지 연산을 쓸 때는 0인 경우에 대해서도 충분히 생각해야 합니다.

code: programers 150370 개인정보 수집 유효기간

---

raquelkim/location.cpp

시간이 없어서 준비가 미흡하고,, 코드 설명도 적지 못했습니다... 
분발하겠습니다...!

code : 김진경 programmers location

---

raquelkim/privacy.cpp

시간이 없어서 준비가 미흡하고,, 코드 설명도 적지 못했습니다... 
분발하겠습니다...!

code : 김진경 프로그래머스 개인정보

---

lnk0308/Programmers/160585.py

[문제 보러가기](https://school.programmers.co.kr/learn/courses/30/lessons/160585)
게임 판 정보를 순차적으로 확인하여 선공, 후공 정보를 각각 저장한 뒤에, 게임에서 발생할 수 있는 경우를 
조건문을 통해 구현하고자 했습니다. 
1. 구하고자 하는 값 파악 
- 게임의 정상 진행 여부를 flag 값으로 출력 
1) 정상적으로 진행된 경우: 1 
2) 비정상적으로 진행된 경우: 0
2. 각 변수로부터 얻을 수 있는 값 파악  
1) 게임판 정보 리스트 (board)  
- O의 좌표 위치
- X의 좌표 위치 
3. 풀이 방식  
1) 입력 받은 게임판 정보(board)를 순차적으로 탐색하며, o와 x의 좌표 위치를 각각의 리스트에 저장 
2) 게임에서 발생할 수 있는 경우의 수를 크게 3가지의 경우로 나누어 판단 진행 
CASE 1) 3줄이 아예 생기지 않았을 경우 
CASE 2) 선공(O)이 3개가 만들어져 이겼을 경우
CASE 3) 후공(X)가 3개 만들어져 이겼을 경우  
-> 3개가 만들어졌는지 판단하는 함수를 별도로 구현 
```python
def check_Tic(check_lists):
row = [0,0,0] 
col = [0,0,0]
cross = [0,0] 
#위치 좌표를 순차적으로 확인 진행 
for check_list in check_lists:
row[check_list[0]]+=1 # 좌표의 첫번째 수는 행의 위치를 의미 
col[check_list[1]]+=1 # 좌표의 두번째 수는 열의 위치를 의미 
if check_list …
```

이남규 Programmers 160585 혼자서 하는 틱택토

---

hyeonsook95/programers/160585.py

[문제 보러가기](https://school.programmers.co.kr/learn/courses/30/lessons/160585)
게임판이 3*3으로 제한되어 있고, 규칙을 어기는 실수가 2개로 정의되어 있었기 때문에 규칙에 위배되는 경우를 추론하면 될 것이라 생각하고 불가능한 경우를 찾았습니다.
> 1. 선공과 후공이 모두 승리했다.
> 2. 선공의 알의 개수는 후공의 알의 개수보다 1개 많거나 같아야 한다.
> 3. 선공이 이겼을 때는 선공의 알의 개수가 1개 더 많아야 하고, 후공이 이겼을 때는 두 알의 개수가 같아야 한다.
주어진 데이터에서 계산해야 할 값들은 선공과 후공의 알의 개수, 선공과 후공이 이긴 횟수입니다.
알의 개수는 int 값으로 필요한 게 아니라 **두 알의 개수의 차이** 값이 필요하고, **이긴 횟수**를 알기 위해서는 보드의 위치에 따라 한 줄에 모두 같은 알이 존재하는지의 여부가 필요하기 때문에 -1. 0, 1 로 값을 채우고 계산하려고 했습니다.
```
b = { 'O': 1, '.': 0, 'X': -1 }
board = [ [ b[board[r][c]] for c in range(3) ] for r in range(3) ]
```
**두 알의 개수의 차이** 값을 알기 위해 보드의 모든 값을 더하고, 양수이면 선공의 알의 개수가 많은 것, 음수이면 후공의 알의 개수가 많은 것으로 계산합니다.
```
sum_board = sum(sum(board, []))
```
**이긴 횟수**를 계산하기 위해 행의 합과 열의 합이 각각 3이면 선공의 승리, -3이면 후공의 승리로 …

code : programers 160585 혼자서 하는 틱택톡

---

lnk0308/Programmers/150370.py

[문제 보러가기](https://school.programmers.co.kr/learn/courses/30/lessons/150370)
리스트를 쭈욱 돌면서 조건문을 통해 파기 대상을 찾아야겠다고 판단 후 풀이를 시작했습니다.    
얻을 수 있는 정보와 얻어야 하는 정보를 정리하며 순차적으로 구현하며 풀이를 진행했습니다. 
1. 구하고자 하는 값 파악 
- 파기해야 할 개인 정보 번호의 오름차순 출력 
2. 각 변수로부터 얻을 수 있는 값 파악  
1) 개인정보 리스트 (privacies) 
- 개인정보 수집 일자
- 해당 정보의 약관 종류 
2) 약관 정보 리스트 (terms)
- 약관 종류 
- 유효 기간
3) 파기의 여부를 판단하는 기준이 되는 오늘 날짜 (today) 
3. 풀이 방식  
1) 파악 대상인 개인정보 리스트를 처음부터 끝까지 하나씩 확인 
2) 개인정보 리스트로부터 얻은 약관 종류를 가지고, 약관 정보 리스트로부터 유효 기간 얻기 
3) 월 기간을 의미하는 유효 기간을 년 월 정보로 환산 
4) 년 월로 환산 된 유효 기간을 개인정보 수집 일자에 더해 파기 일자 얻기 
5) 3가지 조건문을 통해 파기 대상 여부를 확인 
6) 개인정보의 번호는 개인정보 리스트의 인덱스를 의미하므로, 인덱스 정보를 리스트 정보에 넣고 오름차순 후 출력          
```python
def solution(today, terms, privacies):
answer = []    
#개인정보 탐색 
for num in range(len(privacies)):
privacy = privacies[num] …
```

code: 이남규 Programmers 150370 개인정보 수집 유효기간
